version: "3"

services:
  postgres:
    image: postgres:11.10
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    restart: always
